// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.2
// source: cos.proto

package protos

import (
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const ()

// CosServiceClient is the client API for CosService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CosServiceClient interface {
}

type cosServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCosServiceClient(cc grpc.ClientConnInterface) CosServiceClient {
	return &cosServiceClient{cc}
}

// CosServiceServer is the server API for CosService service.
// All implementations must embed UnimplementedCosServiceServer
// for forward compatibility
type CosServiceServer interface {
	mustEmbedUnimplementedCosServiceServer()
}

// UnimplementedCosServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCosServiceServer struct {
}

func (UnimplementedCosServiceServer) mustEmbedUnimplementedCosServiceServer() {}

// UnsafeCosServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CosServiceServer will
// result in compilation errors.
type UnsafeCosServiceServer interface {
	mustEmbedUnimplementedCosServiceServer()
}

func RegisterCosServiceServer(s grpc.ServiceRegistrar, srv CosServiceServer) {
	s.RegisterService(&CosService_ServiceDesc, srv)
}

// CosService_ServiceDesc is the grpc.ServiceDesc for CosService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CosService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cos.CosService",
	HandlerType: (*CosServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "cos.proto",
}
